name: Snapcraft
on: [push, pull_request]
jobs:
  snap:
    runs-on: ubuntu-latest
    steps:
      - name: Install build dependencies
        shell: bash
        run: |
          set -euxo pipefail
          sudo apt remove --purge lxd lxd-client 
          sudo snap install snapcraft --edge --classic
          sudo snap install lxd
          sudo lxd waitready
          sudo lxd init --auto
          sudo chmod 0666 /var/snap/lxd/common/lxd/unix.socket
          echo "/snap/bin" >> $GITHUB_PATH

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        shell: bash
        run: |
          set -euxo pipefail
          snapcraft snap --use-lxd

      - name: Install built snap
        shell: bash
        run: |
          set -euxo pipefail
          sudo snap install *.snap --dangerous --devmode

      - name: Smoke test
        shell: bash
        run: |
          set -euxo pipefail
          sudo apt install -y lsscsi
          sudo modprobe scsi_debug add_host=1 dev_size_mb=200 per_host_store=1
          sudo microceph init
          sleep 5
          echo
          echo
          sudo microceph.ceph -s
          for raw_disk in $(sudo lsscsi|awk '/scsi_debug/{print$6}'); do
              sudo microceph.ceph-volume lvm prepare \
                  --data $raw_disk
          done
          sudo microceph.ceph-volume lvm activate --all || true
          sleep 5
          echo
          echo
          sudo microceph.ceph -s
