name: Build and test confined snap
on: [push, pull_request]
jobs:
  snap:
    runs-on: ubuntu-18.04
    steps:
      - name: Install build dependencies
        shell: bash
        run: |
          set -euxo pipefail
          sudo apt remove --purge lxd lxd-client
          # for in-flight snapd interfaces
          sudo add-apt-repository -y ppa:fnordahl/dev
          sudo apt -y install snapd
          sudo snap install snapcraft --edge --classic
          sudo snap install lxd
          sudo lxd waitready
          sudo lxd init --auto
          sudo chmod 0666 /var/snap/lxd/common/lxd/unix.socket
          echo "/snap/bin" >> $GITHUB_PATH

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        shell: bash
        run: |
          set -euxo pipefail
          snapcraft snap --use-lxd

      - name: Install built snap
        shell: bash
        run: |
          set -euxo pipefail
          sudo snap install *.snap --dangerous

      - name: Smoke test
        shell: bash
        run: |
          set -euxo pipefail
          for interface in \
                  block-devices \
                  hardware-observe \
                  lvm-control \
                  lvm-support \
                  mount-observe \
                  network \
                  network-bind \
                  network-control \
                  tmpfs-mount \
                  ; do
              sudo snap connect microceph:$interface
          done
          # NOTE: The kernel version used does not have per_host_store support
          # so we can only use one block device from scsi_debug
          sudo modprobe scsi_debug add_host=1 dev_size_mb=200
          sudo apt -y install lsscsi
          sudo microceph init
          sleep 5
          echo
          echo
          sudo microceph.ceph -s
          for raw_disk in $(sudo lsscsi|awk '/scsi_debug/{print$6}'); do
              sudo microceph.ceph-volume lvm prepare \
                  --data $raw_disk
          done
          sleep 5
          echo
          echo
          sudo microceph.ceph -s
